---
kind: Template
apiVersion: v1
metadata:
  name: jaeger
  creationTimestamp:
parameters:
  - name: APP_NAME
    displayName: App Name
    description: Used to group components together in the OpenShift console.
    required: true
    value: monitoring
  - name: SOURCE_IMAGE_TAG
    displayName: Source Image Tag
    description: The tag of the source image.
    required: true
    value: "1.18.1"
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: "jaeger-query"
      labels:
        shared: "true"
        app: "${APP_NAME}"
      annotations: {}
    spec:
      lookupPolicy:
        local: false
      tags:
        - name: "${SOURCE_IMAGE_TAG}"
          annotations:
          from:
            kind: DockerImage
            name: "jaegertracing/jaeger-query:${SOURCE_IMAGE_TAG}"
          generation: 1
          importPolicy: {}
          referencePolicy:
            type: Local
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: "jaeger-collector"
      labels:
        shared: "true"
        app: "${APP_NAME}"
      annotations: {}
    spec:
      lookupPolicy:
        local: false
      tags:
        - name: "${SOURCE_IMAGE_TAG}"
          annotations:
          from:
            kind: DockerImage
            name: "jaegertracing/jaeger-collector:${SOURCE_IMAGE_TAG}"
          generation: 1
          importPolicy: {}
          referencePolicy:
            type: Local
