name: Build and push to AWS
on:
  pull_request:
    paths:
      - ".github/workflows/frontend-build.yaml"
      - "services/core-web/**"
      - "!**/README.md"

env:
  IMAGE_URI: ${{ secrets.AWS_ECR_URI }}
  SERVICE_CONTEXT: services/core-web

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        include:
        - service: services/core-web
          repo: mds
        - service: services/core-api
          repo: mds

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Capture changes to build for
        id: changes
        # parses out special characters that cause hidden output truncation
        # TODO: compare this branch to develop instead of just last commit
        run: |
          CHANGES=$(git diff --name-only HEAD HEAD~1)
          CHANGES="${CHANGES//'%'/'%25'}"
          CHANGES="${CHANGES//$'\n'/'%0A'}"
          CHANGES="${CHANGES//$'\r'/'%0D'}"
          echo "::set-output name=changelist::$CHANGES"

      - name: Skip if no changes for this service
        if: contains(steps.changes.outputs.changelist, matrix.service) == false
        id: detected
        run: |
            echo "::set-output name=do_build::false"
            echo "No changes in this service - skipping build..."

      - name: Configure AWS credentials
        if: steps.detected.outputs.do_build != "false"
        uses: aws-actions/configure-aws-credentials@v1.5.8
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 900
          role-session-name: mds-github-action
          role-skip-session-tagging: true

      - name: Login to Amazon ECR
        if: steps.detected.outputs.do_build != "false"
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - uses: actions/cache@v2
        if: steps.detected.outputs.do_build != "false"
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Docker Buildx
        if: steps.detected.outputs.do_build != "false"
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        if: steps.detected.outputs.do_build != "false"
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          context: ${{ env.SERVICE_CONTEXT }}
          push: true
          tags: ${{ env.IMAGE_URI }}:${{ github.sha }}