name: Build and push to AWS

on:
  push:
    branches:
      - "main"

env:
  IMAGE_URI: ${{ secrets.AWS_ECR_URI }}
  TAG_ENV: dev

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        include:
          - service: services/core-web
            repo: mds-web
          - service: services/core-api
            repo: mds-api
          - service: migrations
            repo: mds-flyway

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: fetch working tree info
        run: |
          git fetch --no-tags --prune origin ${{ github.ref }}

      - name: Capture changes to build for
        id: changes
        # gets list of files changed between this branch and develop
        # parses out special characters that cause hidden output truncation
        run: |
          CHANGES=$(git diff --name-only ${{ github.ref }}~1 ${{ github.ref }})
          CHANGES="${CHANGES//'%'/'%25'}"
          CHANGES="${CHANGES//$'\n'/'%0A'}"
          CHANGES="${CHANGES//$'\r'/'%0D'}"
          echo "::set-output name=changelist::$CHANGES"

      - name: Skip if no changes for this service
        if: contains(steps.changes.outputs.changelist, matrix.service) == false
        id: detected
        run: |
          echo "::set-output name=do_build::no"
          echo "No changes in this service - skipping build..."

      - name: Configure AWS credentials
        # if: steps.detected.outputs.do_build != 'no'
        uses: aws-actions/configure-aws-credentials@v1.5.8
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 900
          role-session-name: mds-github-action
          role-skip-session-tagging: true

      - name: Login to Amazon ECR
        if: steps.detected.outputs.do_build != 'no'
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - uses: actions/cache@v2
        # if: steps.detected.outputs.do_build != 'no'
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Docker Buildx
        if: steps.detected.outputs.do_build != 'no'
        uses: docker/setup-buildx-action@v1

      # TODO: seperate real push to avoid half-built release
      - name: Build and push
        # if: steps.detected.outputs.do_build != 'no'
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          context: ${{ matrix.service }}
          push: true
          tags: ${{ env.IMAGE_URI }}${{ matrix.repo }}:${{ github.sha }}, ${{ env.IMAGE_URI }}${{ matrix.repo }}:${{ env.TAG_ENV }}
