name: Promote test to prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_URI: ${{ secrets.AWS_ECR_URI }}
  TAG_ENV: test
  TAG_PROMOTE: prod

jobs:
  promote-to-prod:
    name: promote-to-prod
    runs-on: ubuntu-20.04
    # Note the lack of fail-fast, this is on purpose
    # not all images will have been built with this sha as a tag
    strategy:
      matrix:
        include:
          - repo: mds-web
          - repo: mds-api
    environment:
      name: production

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.5.8
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 900
          role-session-name: mds-github-action
          role-skip-session-tagging: true

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Pull and tag with dev
        run: |
          docker pull ${{ env.IMAGE_URI }}${{ matrix.repo }}:${{ env.TAG_ENV }}
          docker tag ${{ env.IMAGE_URI }}${{ matrix.repo }}:${{ env.TAG_ENV }} ${{ env.IMAGE_URI }}${{ matrix.repo }}:${{ env.TAG_PROMOTE }}
          docker push ${{ env.IMAGE_URI }}${{ matrix.repo }} --all-tags
        continue-on-error: true

      - name: Update service tasks
        if: ${{ success() }}
        run: |
          aws ecs update-service --cluster=mds-cluster --service=${{ matrix.repo }}-service --force-new-deployment
        continue-on-error: true # Remove once in prod
